// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table silver_environment_clean (city:string, country:string, latitude:real, longitude:real, event_time:datetime, event_date:datetime, event_hour:int, temp_c:real, humidity_percent:int, wind_kph:real, uv_index:real, uv_band:string, pm2_5:real, pm10:real, co:real, no2:real, o3:real, aqi_index:int, aqi_band:string, ingestion_time:datetime) with (folder = "Silver") 
.create-merge table weather_Raw_data (city:string, country:string, lat:real, lon:real, localtime:datetime, temp_c:real, humidity:int, wind_kph:real, uv:real, condition_text:string, us_epa_index:int, ingestion_time_utc:datetime, pm2_5:real, pm10:real, co:real, no2:real, o3:int, so2:real) with (folder = "Bronze") 
.alter table weather_Raw_data policy retention @'{"SoftDeletePeriod":"30.00:00:00","Recoverability":"Enabled"}'
